defaultLanguage: en-crrsa

languages:
  - code: en-crrsa
    label: English
    active: true
  - code: am
    label: አማርኛ
    active: true

info:
  enableEndUserAgreement: false
  enablePrivacyStatement: false